# -*- coding: utf-8 -*-
"""final songs recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LXIEmCttT-8PAaFfcnvRd5VmheBK-oVc

# libraries
"""

import pandas as pd
import nltk
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
from nltk.stem.porter import PorterStemmer
nltk.download("punkt")
nltk.download("punkt_tab")

"""# Load dataset"""

url = "https://drive.google.com/uc?export=download&id=12W8B6Q2SKXawlo28pMqJk9t_QRcnpn1D"
df = pd.read_csv(url)
df = df.drop(columns=["link"], errors="ignore")

"""# Cleaning text"""

df["text"] = df["text"].str.lower().replace(r"\n", " ", regex=True)

stemmer = PorterStemmer()
def stem_text(text):
    return " ".join(stemmer.stem(w) for w in nltk.word_tokenize(text))

df["text"] = df["text"].apply(stem_text)

"""# TF-IDF"""

tfidf = TfidfVectorizer(stop_words="english", max_features=10000)
tfidf_matrix = tfidf.fit_transform(df["text"])

# Nearest Neighbors (NO COSINE MATRIX)
nn_model = NearestNeighbors(metric="cosine", algorithm="brute", n_neighbors=6)
nn_model.fit(tfidf_matrix)

pickle.dump(df, open("dfmusic.pkl", "wb"))
pickle.dump(tfidf, open("tfidf_vectorizer.pkl", "wb"))
pickle.dump(nn_model, open("song_nn_model.pkl", "wb"))